// Records actual local UI execution, with an explicit test-network label.
const {chromium}=require('playwright'),fs=require('node:fs');
(async()=>{
 fs.mkdirSync('demo',{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome',args:['--disable-gpu','--window-size=1600,1000']}),context=await browser.newContext({viewport:{width:1600,height:900},colorScheme:'light',recordVideo:{dir:'demo/raw',size:{width:1600,height:900}}}),page=await context.newPage();page.setDefaultTimeout(15000);const start=Date.now(),scenes=[];
 const f=page.frameLocator('iframe');const hold=ms=>page.waitForTimeout(ms);
 async function scene(text){scenes.push({start:(Date.now()-start)/1000,text});await page.locator('#scene').evaluate((el,t)=>el.textContent=t,text);}
 async function click(name){const button=f.getByRole('button',{name,exact:true});await button.scrollIntoViewIfNeeded();await hold(400);await button.click();await page.waitForFunction(()=>!document.querySelector('iframe').contentDocument.querySelector('button[disabled]'));if(await f.locator('[role=alert]').count())throw Error(await f.locator('[role=alert]').innerText());await hold(650);}
 async function sign(){await f.getByRole('region',{name:'Transaction review'}).waitFor();await hold(2400);await click('Sign & submit local transaction');await hold(800);}
 try{
 await page.goto('http://127.0.0.1:5180/demo-frame.html');await f.getByRole('button',{name:'Add test SOL',exact:true}).waitFor();await scene('Launch on agreed terms. Or recover funds.');await hold(3500);
 await scene('01 / Publish fixed launch terms');await click('Add test SOL');await click('Create a launch →');await f.getByLabel('Token name',{exact:true}).fill('Community launch');await click('Review campaign transaction');await sign();
 await scene('02 / Fund together, before the deadline');await f.getByLabel('Test wallet',{exact:true}).selectOption('1');await hold(500);await click('Add test SOL');await f.getByLabel('Contribution · SOL',{exact:true}).fill('3');await click('Review contribution');await sign();
 await scene('03 / Anyone can execute the agreed launch');await f.getByText('Local rehearsal controls',{exact:true}).click();await click('Advance to funding close');await click('Execute the launch');await sign();
 await scene('04 / Claim tokens and excess SOL');await click('Claim tokens & excess SOL');await sign();await f.getByRole('heading',{name:'Continue trading'}).scrollIntoViewIfNeeded();await hold(2200);
 await scene('05 / Continue through DBC into DAMM');await click('Add test SOL');await f.getByLabel('Direction',{exact:true}).selectOption('buy');await f.getByLabel('Amount · SOL',{exact:true}).fill('12');await click('Review trade');await sign();await click('Complete DAMM v2 migration');await sign();await f.getByLabel('Direction',{exact:true}).selectOption('sell');await f.getByLabel('Amount · COMM',{exact:true}).fill('1000');await click('Review trade');await sign();
 await scene('06 / Failed launch? Recover your contribution');await f.getByLabel('Test wallet',{exact:true}).selectOption('0');await hold(500);await click('Create a launch →');await f.getByLabel('Token name',{exact:true}).fill('Refund rehearsal');await click('Review campaign transaction');await sign();await f.getByLabel('Test wallet',{exact:true}).selectOption('2');await hold(500);await click('Add test SOL');await f.getByLabel('Contribution · SOL',{exact:true}).fill('0.5');await click('Review contribution');await sign();await f.getByText('Local rehearsal controls',{exact:true}).click();await click('Advance to funding close');await click('Recover contribution');await sign();
 await scene('Try the working local rehearsal');await hold(4500);
 const end=(Date.now()-start)/1000,format=s=>{let n=Math.round(s*1000);return [Math.floor(n/3600000),Math.floor(n/60000)%60,Math.floor(n/1000)%60].map(x=>String(x).padStart(2,'0')).join(':')+','+String(n%1000).padStart(3,'0');};fs.writeFileSync('demo/captions.srt',scenes.map((s,i)=>`${i+1}\n${format(s.start)} --> ${format(scenes[i+1]?.start||end)}\n${s.text}\n`).join('\n'));fs.writeFileSync('demo/storyboard.json',JSON.stringify({network:'local rehearsal',duration:end,scenes},null,2));
 }finally{const video=page.video();await context.close();await video.saveAs('demo/local-rehearsal.webm');await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
