// Local rehearsal only. Wallet transactions are signed by the browser, never here.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {Keypair,PublicKey,Transaction}=require('@solana/web3.js'),BN=require('bn.js');
const dbc=require('@meteora-ag/dynamic-bonding-curve-sdk'),damm=require('@meteora-ag/cp-amm-sdk');
const {getAssociatedTokenAddressSync}=require('@solana/spl-token');
const lc=require('../sdk/index.cjs'),{createEnvironment}=require('./vm.cjs'),{preset}=require('./preset.cjs');
const {binary}=require('../tests/harness.cjs');
const pid=Keypair.generate().publicKey,e=createEnvironment({programId:pid.toBase58(),programPath:binary(),now:Math.floor(Date.now()/1000)}),dc=new dbc.DynamicBondingCurveClient(e.connection,'confirmed'),cp=new damm.CpAmm(e.connection),setupFunder=Keypair.generate();e.fund(setupFunder.publicKey.toBase58(),1000000000000n);
const configs=new Map();let nonce=1n;
function parse(value,decimals=9){if(typeof value!=='string'||!new RegExp('^[0-9]+(?:\\.[0-9]{1,'+decimals+'})?$').test(value))throw Error('Enter a positive decimal amount with at most '+decimals+' decimal places.');const [a,b='']=value.split('.');const n=BigInt(a)*10n**BigInt(decimals)+BigInt(b.padEnd(decimals,'0'));if(n<=0n||n>18446744073709551615n)throw Error('Amount is out of range.');return n;}
function read(k){const ac=e.account(k.toBase58());if(!ac?.owner.equals(pid))throw Error('Campaign not found.');return lc.decodeCampaign(ac.data);}
const now=()=>e.vm.getClock().unixTimestamp;
async function configFor(owner){const id=owner.toBase58();if(configs.has(id))return configs.get(id);const k=Keypair.generate(),p=preset();await e.execute(await dc.partner.createConfig({config:k.publicKey,feeClaimer:owner,leftoverReceiver:owner,payer:setupFunder.publicKey,quoteMint:lc.WSOL_MINT,...p}),[setupFunder,k]);configs.set(id,k.publicKey);return k.publicKey;}
async function state(wallet){const person=new PublicKey(wallet),campaigns=[];for(const key of e.known){const a=e.account(key);if(!a?.owner.equals(pid)||a.data.length!==lc.CAMPAIGN_SIZE)continue;let c;try{c=lc.decodeCampaign(a.data);}catch{continue;}const phase=lc.phase(c,now()),campaign=new PublicKey(key),rp=lc.deriveReceipt(pid,campaign,person)[0],ra=e.account(rp.toBase58());let receipt=null;try{if(ra?.owner.equals(pid))receipt=lc.decodeReceipt(ra.data);}catch{}
 const pos=receipt?{contribution:receipt.amount,tokens:0n,excess:0n}:null;if(pos&&phase==='settled')Object.assign(pos,lc.allocation({contribution:receipt.amount,total:c.totalContributed,target:c.target,bought:c.tokensBought}));
 const boundConfig=lc.decodeDbcConfig(e.account(c.config.toBase58()).data);
 let venue='DBC bonding curve',canMigrate=false;if(phase==='settled'){const pool=dbc.deriveDbcPoolAddress(lc.WSOL_MINT,c.mint,c.config),vp=await dc.state.getPool(pool);if(vp?.poolState.isMigrated)venue='DAMM v2';else if(vp?.poolState.finishCurveTimestamp.gt(new BN(0))){venue='Awaiting DAMM v2 migration';canMigrate=true;}}
 campaigns.push({address:key,name:c.name,symbol:c.symbol,target:c.target,total:c.totalContributed,closeTime:c.closeTime,expiry:c.expiry,progress:Number(c.totalContributed)*100/Number(c.target),status:phase,statusLabel:{funding:'Funding open',settleable:'Ready to launch',refundable:'Refunds available',settled:'Launched'}[phase],canContribute:phase==='funding',canWithdraw:phase==='funding',canSettle:phase==='settleable',canRefund:phase==='refundable',venue,canMigrate,positions:pos?{[wallet]:pos}:{},walletTokenBalance:e.account(getAssociatedTokenAddressSync(c.mint,person).toBase58())?.data.readBigUInt64LE(64)||0n,config:c.config.toBase58(),configHash:c.configHash,configMatches:lc.hashConfig(e.account(c.config.toBase58()).data)===c.configHash,mint:c.mint.toBase58(),beneficiary:c.beneficiary.toBase58(),minTokens:c.minTokens,decimals:boundConfig.tokenDecimal,supply:boundConfig.preMigrationTokenSupply,migrationThreshold:boundConfig.migrationQuoteThreshold,creatorTradingFeePercentage:boundConfig.creatorTradingFeePercentage,partnerFeeRecipient:boundConfig.feeClaimer.toBase58(),creatorLockedLiquidity:boundConfig.creatorPermanentLockedLiquidityPercentage,partnerLockedLiquidity:boundConfig.partnerPermanentLockedLiquidityPercentage});}
 return {network:'local',programId:pid.toBase58(),balance:await e.connection.getBalance(person),now:now(),campaigns};}
async function prepare(data){const wallet=new PublicKey(data.wallet),campaign=data.campaign?new PublicKey(data.campaign):null;let built,summary,title,quoteDetails,extra=[],createdCampaign,note='This transaction uses a temporary local test wallet. Network fees and setup costs are separate from contributed principal.';
 if(data.action==='create'){const target=parse(data.target),minutes=Number(data.minutes);if(!Number.isInteger(minutes)||minutes<1||minutes>1440)throw Error('Choose a funding window from 1 to 1,440 minutes.');const cfg=await configFor(wallet),p=preset(),cs=await dc.state.getPoolConfig(cfg);if(target>=BigInt(cs.migrationQuoteThreshold.toString()))throw Error('The target must be below the preset’s migration threshold. Try 2 SOL.');const q=dc.pool.getQuoteFromInputAmount({config:p,swapBaseForQuote:false,swapMode:0,amountIn:new BN(target.toString()),slippageBps:1});built=await lc.createCampaign({programId:pid,organizer:wallet,beneficiary:wallet,config:cfg,nonce:nonce++,target,minTokens:BigInt(q.minimumAmountOut.toString()),closeTime:now()+BigInt(minutes*60),expiry:now()+BigInt((minutes+10)*60),budgetLamports:100000000n,name:data.name,symbol:data.symbol,uri:'https://example.invalid/local-campaign.json'});quoteDetails={expectedTokens:q.amountOut?.toString()||q.minimumAmountOut.toString(),minimumTokens:q.minimumAmountOut.toString(),decimals:6};createdCampaign=built.campaign.toBase58();title='Create campaign';summary='Publish the launch terms and fund a separate 0.1 SOL setup budget, plus account rent. Setup budget and campaign rent are not recoverable in this version. The local faucet separately pays for the reusable DBC configuration.';}
 else {if(!campaign)throw Error('Select a campaign first.');const c=read(campaign),common={connection:e.connection,programId:pid,campaign,contributor:wallet};
 switch(data.action){case 'contribute':{const amount=parse(data.amount);built=await lc.contribute({...common,amount});title='Contribute SOL';summary=`Commit ${data.amount} SOL. You can withdraw before funding closes. Your final share depends on all contributions at close.`;break;}
 case 'withdraw':{const rp=lc.deriveReceipt(pid,campaign,wallet)[0],r=e.account(rp.toBase58());if(!r)throw Error('No contribution to withdraw.');built=await lc.withdraw({...common,amount:lc.decodeReceipt(r.data).amount});title='Withdraw contribution';summary='Return your entire contribution and receipt rent before the funding window closes.';break;}
 case 'settle':built=await lc.settle(common);title='Execute the launch';summary='Create the token and DBC pool, then spend exactly the published target. Contributors’ tokens and excess SOL become claimable. You pay only the network fee; the organizer’s separate budget pays setup rent.';break;
 case 'claim':built=await lc.claim(common);title='Claim allocation and excess';summary='Receive your proportional token allocation and any excess SOL. The program closes your contribution receipt so it cannot be claimed again.';break;
 case 'refund':built=await lc.refund(common);title='Recover contribution';summary='Return your full recorded contribution and receipt rent. Network fees paid for earlier transactions are not refundable. This action does not call Meteora.';break;
 case 'migrate':{const pool=dbc.deriveDbcPoolAddress(lc.WSOL_MINT,c.mint,c.config),cfg=await dc.state.getPoolConfig(c.config),m=await dc.migration.migrateToDammV2({pool,dammConfig:dbc.DAMM_V2_MIGRATION_FEE_ADDRESS[cfg.migrationFeeOption],payer:wallet});built=m;extra=[m.firstPositionNftKeypair,m.secondPositionNftKeypair];title='Migrate to DAMM v2';summary='Create the successor liquidity pool using the published configuration. This caller pays migration account rent in addition to the network fee.';break;}
 case 'trade':{const sell=data.direction==='sell',amount=parse(data.amount,sell?6:9),pool=dbc.deriveDbcPoolAddress(lc.WSOL_MINT,c.mint,c.config),vp=await dc.state.getPool(pool),cfg=await dc.state.getPoolConfig(c.config);if(vp.poolState.isMigrated){const dp=dbc.deriveDammV2PoolAddress(dbc.DAMM_V2_MIGRATION_FEE_ADDRESS[cfg.migrationFeeOption],c.mint,lc.WSOL_MINT),ps=await cp.fetchPoolState(dp),input=sell?c.mint:lc.WSOL_MINT,output=sell?lc.WSOL_MINT:c.mint,q=cp.getQuote({inAmount:new BN(amount.toString()),inputTokenMint:input,slippage:0.5,poolState:ps,currentTime:Number(now()),currentSlot:Number(e.vm.getClock().slot),tokenADecimal:6,tokenBDecimal:9,hasReferral:false});quoteDetails={minimumReceived:q.minSwapOutAmount.toString(),decimals:sell?9:6,symbol:sell?'SOL':c.symbol};built={transaction:await cp.swap2({payer:wallet,pool:dp,inputTokenMint:input,outputTokenMint:output,tokenAMint:ps.tokenAMint,tokenBMint:ps.tokenBMint,tokenAVault:ps.tokenAVault,tokenBVault:ps.tokenBVault,tokenAProgram:damm.getTokenProgram(ps.tokenAFlag),tokenBProgram:damm.getTokenProgram(ps.tokenBFlag),poolState:ps,referralTokenAccount:null,swapMode:0,amountIn:new BN(amount.toString()),minimumAmountOut:q.minSwapOutAmount})};}
 else{if(vp.poolState.finishCurveTimestamp.gt(new BN(0)))throw Error('The curve is complete. Finish migration before trading.');const q=dc.pool.swapQuote2({virtualPool:vp,config:cfg,swapBaseForQuote:sell,swapMode:1,amountIn:new BN(amount.toString()),slippageBps:50,hasReferral:false,currentPoint:new BN(now().toString())});quoteDetails={minimumReceived:q.minimumAmountOut.toString(),decimals:sell?9:6,symbol:sell?'SOL':c.symbol};built={transaction:await dc.pool.swap2({owner:wallet,pool,swapBaseForQuote:sell,swapMode:1,amountIn:new BN(amount.toString()),minimumAmountOut:q.minimumAmountOut,referralTokenAccount:null})};}
 title=sell?'Sell tokens':'Buy tokens';summary=`Trade up to ${data.amount} ${sell?c.symbol:'SOL'} with a 0.5% slippage limit. This purchase is outside the contribution round and can lose value.`;break;}
 default:throw Error('Unknown action.');}}
 const tx=built.transaction;tx.feePayer=wallet;tx.recentBlockhash=e.vm.latestBlockhash();if(extra.length)tx.partialSign(...extra);const wire=tx.serialize({requireAllSignatures:false,verifySignatures:false});if(wire.length>1232)throw Error('Transaction exceeds the supported packet size. No funds were moved.');return {transaction:wire.toString('base64'),title,summary,note,quoteDetails,createdCampaign,fee:5000*(1+extra.length)};
}
let queue=Promise.resolve();
const server=http.createServer((req,res)=>{const allowedOrigins=['http://127.0.0.1:5180','http://localhost:5180'];if(req.headers.origin&&!allowedOrigins.includes(req.headers.origin)){res.writeHead(403);return res.end('Origin not allowed');}const finish=(code,x)=>{res.writeHead(code,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(x,(_,v)=>typeof v==='bigint'?v.toString():v));};let raw='',size=0;req.on('data',chunk=>{size+=chunk.length;if(size>65536){req.destroy();return;}raw+=chunk;});req.on('end',()=>{const run=async()=>{try{const u=new URL(req.url,'http://127.0.0.1'),data=raw?JSON.parse(raw):{};if(req.method==='GET'&&u.pathname==='/api/state')return finish(200,await state(u.searchParams.get('wallet')));if(req.method!=='POST'||req.headers['content-type']!=='application/json')return finish(400,{error:'JSON request required.'});if(u.pathname==='/api/faucet'){e.fund(new PublicKey(data.wallet).toBase58(),10000000000n);return finish(200,{ok:true});}if(u.pathname==='/api/prepare')return finish(200,await prepare(data));if(u.pathname==='/api/send'){const bytes=Buffer.from(data.transaction,'base64');if(bytes.length>1232)throw Error('Transaction too large.');const simulation=e.simulate(bytes);if(!simulation.ok){const err=Error(simulation.error);err.logs=simulation.logs;throw err;}return finish(200,e.send(bytes));}if(u.pathname==='/api/advance'){const c=read(new PublicKey(data.campaign)),to=data.to==='expiry'?c.expiry:c.closeTime;e.advance(Math.max(0,Number(to-now())));return finish(200,{now:now()});}finish(404,{error:'Route not found.'});}catch(err){const logs=err.logs||[];const code=logs.map(x=>x.match(/custom program error: 0x([0-9a-f]+)/)?.[1]).filter(Boolean).at(-1);const name=code?lc.ERRORS?.[parseInt(code,16)]:null;finish(400,{error:name?`${name}: ${err.message}`:err.message,logs});}};queue=queue.then(run,run);});});
server.listen(19189,'127.0.0.1',()=>console.log('Local Solana rehearsal API at http://127.0.0.1:19189; temporary state and test funds only.'));
