import React,{useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Buffer} from 'buffer';
import {Keypair,Transaction,VersionedTransaction} from '@solana/web3.js';
import bs58 from 'bs58';
import {registry,availableWallets,accountFor,connectWallet,signWalletTransaction} from './wallet.mjs';
import {createDevnetApi} from './devnet-api.mjs';
import './style.css';
globalThis.Buffer=Buffer;
const money=(n,d=9)=>{let v=BigInt(n||0),base=10n**BigInt(d);return `${(v/base).toLocaleString('en-US')}${v%base?'.'+(v%base).toString().padStart(d,'0').replace(/0+$/,''):''}`};
const short=s=>s?`${s.slice(0,5)}…${s.slice(-5)}`:'—';
const date=n=>new Date(Number(n)*1000).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const directApi=import.meta.env.VITE_DIRECT_RPC==='true'?createDevnetApi({stateDeploymentCacheMs:30000}):null;
async function api(path,data){if(directApi)return directApi(path,data);const r=await fetch('/api/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(path==='send'?90000:20000)});const x=await r.json();if(x.status==='unknown')return x;if(!r.ok||x.error){const e=Error(x.error||'Request failed');e.result=x;throw e;}return x;}
const LOCAL=import.meta.env.VITE_NETWORK!=='devnet';
const wallets=LOCAL?Array.from({length:3},()=>Keypair.generate()):[];
function App(){
 const [state,setState]=useState(null),[selected,setSelected]=useState(new URLSearchParams(location.search).get('campaign')),[role,setRole]=useState(0),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[amount,setAmount]=useState(LOCAL?'1':'0.01'),[creating,setCreating]=useState(false),[preview,setPreview]=useState(null),[receipt,setReceipt]=useState(null),[tradeDirection,setTradeDirection]=useState('buy');
 const [choices,setChoices]=useState(availableWallets),[walletIndex,setWalletIndex]=useState(0),[external,setExternal]=useState(null),[account,setAccount]=useState(null);
 const previewRef=useRef(null);
 useEffect(()=>{const update=()=>setChoices(availableWallets());const a=registry.on('register',update),b=registry.on('unregister',update);return()=>{a();b();};},[]);
 useEffect(()=>{if(!external?.features['standard:events'])return;return external.features['standard:events'].on('change',()=>{setPreview(null);setAccount(accountFor(external,state?.network==='validator'?'solana:localnet':'solana:devnet')||null);});},[external,state?.network]);
 useEffect(()=>{if(preview){previewRef.current?.scrollIntoView({behavior:'smooth',block:'center'});previewRef.current?.focus({preventScroll:true});}},[preview]);
 const key=wallets[role],address=LOCAL?key.publicKey.toBase58():account?.address||'',networkName=LOCAL?'Local Solana runtime':state?.network==='validator'?'Local validator':'Solana devnet',chain=state?.network==='validator'?'solana:localnet':'solana:devnet',campaign=state?.campaigns.find(x=>x.address===selected),position=campaign?.positions?.[address];
 const refresh=async()=>{const x=await api('state?wallet='+address);setState(x);if(!selected&&!new URLSearchParams(location.search).get('campaign')&&x.campaigns.length){choose(x.campaigns[0].address);}return x;};
 function choose(id){setSelected(id);history.replaceState(null,'','?campaign='+id);setPreview(null);setError('');setNotice('');}
 useEffect(()=>{refresh().catch(e=>setError(e.message));if(!LOCAL){const id=setInterval(()=>refresh().catch(()=>{}),15000);return()=>clearInterval(id);}},[address]);
 async function perform(label,fn,refreshAfter=true){if(busy)return;setBusy(label);setError('');setNotice('');try{await fn();if(refreshAfter)await refresh();}catch(e){setError(e.message);}finally{setBusy('');}}
 async function connect(){await perform('Connecting wallet',async()=>{const w=choices[walletIndex];if(!w)throw Error('No compatible wallet detected. Install a Solana Wallet Standard wallet to use devnet.');const a=await connectWallet(w,chain);setExternal(w);setAccount(a);setPreview(null);});}
 async function prepare(action,extra={}){if(!address){setError('Connect your devnet wallet first.');return;}await perform('Preparing transaction',async()=>{const p=await api('prepare',{action,campaign:selected,wallet:address,amount,...extra});setPreview({...p,action});},false);}
 async function confirm(){await perform('Signing and submitting',async()=>{let wire;if(LOCAL){const tx=Transaction.from(Buffer.from(preview.transaction,'base64'));tx.partialSign(key);wire=tx.serialize();}else wire=await signWalletTransaction(external,account,chain,preview.transaction);const signed=Transaction.from(wire),signature=bs58.encode(signed.signature);setReceipt({signature,status:'unknown',bytes:wire.length});let r;try{r=await api('send',{transaction:Buffer.from(wire).toString('base64')});}catch(e){setPreview(null);if(e.result?.status==='failed'||e.result?.status==='rejected')setReceipt({signature,...e.result});else setNotice('Confirmation is unknown. Check the displayed signature before retrying.');throw e;}setReceipt(r);setPreview(null);if(r.status==='unknown'){setNotice('Confirmation is unknown. Check the displayed signature before retrying.');return;}setNotice('Confirmed on '+networkName+'.');if(preview.createdCampaign){choose(preview.createdCampaign);setCreating(false);}});}
 async function fund(){setPreview(null);await perform('Adding test SOL',async()=>{await api('faucet',{wallet:address});setNotice('Added 10 test SOL. These funds have no monetary value.');});}
 async function submitCreate(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));await prepare('create',f);}
 return <><header><a className="wordmark" href={import.meta.env.BASE_URL}>Launch commitments<span>on Meteora</span></a><div className="wallet"><span className="badge">{LOCAL?"Local rehearsal":networkName}</span>{LOCAL?<><label className="sr" htmlFor="wallet">Test wallet</label><select id="wallet" value={role} onChange={e=>{setPreview(null);setRole(Number(e.target.value));}} disabled={!!busy}><option value="0">Organizer</option><option value="1">Contributor A</option><option value="2">Contributor B</option></select></>:<><label className="sr" htmlFor="external-wallet">Wallet</label><select id="external-wallet" value={walletIndex} disabled={!!busy} onChange={e=>{setWalletIndex(Number(e.target.value));setAccount(null);setExternal(null);setPreview(null);}}>{choices.length?choices.map((w,i)=><option key={i} value={i}>{w.name}</option>):<option>No wallet detected</option>}</select><button disabled={!!busy} onClick={connect}>{account?"Reconnect wallet":"Connect wallet"}</button></>}<button className="quiet" disabled={!address} title={address} onClick={()=>navigator.clipboard.writeText(address).then(()=>setNotice('Wallet address copied.')).catch(()=>setError('Clipboard unavailable.'))}>{short(address)}</button></div></header>
 <main><div className="rehearsal"><span>Real program execution. Test funds only.</span><span>{LOCAL?"State resets when the local server stops. Test wallets reset on page reload.":"Your wallet signs. Campaign terms and contributions are stored on chain."}</span></div>
 {!LOCAL&&state?.deployment&&<details className="deployment"><summary>{state.deployment.upgradeable?'Test deployment · program can be upgraded':'Deployment · program has no upgrade authority'}</summary><p>{state.deployment.upgradeable?'An upgrade authority can replace this program and change how it handles funds. Published campaign terms do not remove that trust assumption. Use devnet test funds only.':'This program currently has no upgrade authority. Its Meteora dependencies have their own deployment controls.'}</p><dl><div><dt>Program</dt><dd className="mono break">{state.programId}</dd></div><div><dt>Upgrade authority</dt><dd className="mono break">{state.deployment.upgradeAuthority||'None'}</dd></div><div><dt>Reviewed build</dt><dd className="mono break">{state.deployment.sha256}</dd></div></dl><p className="small">The deployed code matched this release when checked. This is not a security audit.</p>{state.network==='devnet'&&<a href={'https://explorer.solana.com/address/'+state.programId+'?cluster=devnet'} target="_blank" rel="noreferrer">Inspect deployment on Solana Explorer ↗</a>}</details>}
 <section className="intro"><div><p className="eyebrow">A shared launch. Published terms.</p><h1>Commit together.<br/>Launch on agreed terms.</h1><p className="lede">Contribute during the funding window. Receive a proportional token allocation when the launch executes, or recover your contribution if it doesn’t.</p></div><div className="intro-action"><p className="label">Your test balance</p><strong className="balance">{state?money(state.balance):'…'} <small>SOL</small></strong>{LOCAL?<button onClick={fund} disabled={!!busy}>Add test SOL</button>:<a href="https://faucet.solana.com" target="_blank" rel="noreferrer">Get devnet test SOL ↗</a>}<button className="quiet" onClick={()=>{setCreating(!creating);setPreview(null);}} disabled={!!busy}>{creating?'Close form':'Create a launch →'}</button></div></section>
 {error&&<div className="alert error" role="alert"><strong>Action not completed</strong><p>{error}</p><button className="quiet" onClick={()=>perform('Refreshing',refresh)}>Refresh state</button></div>}{notice&&<div className="alert" role="status">{notice}</div>}
 {creating&&<section className="panel create"><div><p className="eyebrow">New campaign</p><h2>Set the terms once.</h2><p>Contributions cannot change the token, launch target, fee rules or deadlines. This version uses one supported Meteora preset.</p></div><form onSubmit={submitCreate}><div className="form-grid"><label>Token name<input name="name" autoComplete="off" required maxLength="24" defaultValue="Community launch"/></label><label>Symbol<input name="symbol" autoComplete="off" required maxLength="8" defaultValue="COMM"/></label><label>Launch target · SOL<input name="target" inputMode="decimal" autoComplete="off" required defaultValue={!LOCAL&&state?.network==='devnet'?'0.02':'2'} pattern="[0-9]+(\.[0-9]{1,9})?"/></label><label>Funding window · minutes<input name="minutes" inputMode="numeric" autoComplete="off" required defaultValue="10" pattern="[0-9]+"/></label>{!LOCAL&&<label>Token metadata URL<input name="uri" type="url" required placeholder="https://…/metadata.json" maxLength={200}/></label>}</div><p className="small">You pay setup costs separately. All contributed SOL belongs to contributors until settlement. A 10-minute settlement window follows funding close.</p><button className="primary" disabled={!!busy}>Review campaign transaction</button></form></section>}
 {!state&&!error?<section className="panel skeleton" aria-busy="true">Loading campaign accounts…</section>:state?.campaigns.length===0?<section className="panel empty"><h2>No campaigns yet.</h2><p>{LOCAL?"Add test SOL, then create a launch to try the complete funding flow.":"Connect a devnet wallet, get test SOL, then publish a campaign."}</p><button className="primary" onClick={()=>setCreating(true)}>Create the first launch</button></section>:<div className="workspace"><aside><p className="eyebrow">Campaigns</p>{state?.campaigns.map(c=><button key={c.address} className={'campaign-link '+(c.address===selected?'selected':'')} onClick={()=>choose(c.address)}><strong>{c.name}</strong><span>{c.statusLabel} · {money(c.total)} / {money(c.target)} SOL</span></button>)}</aside>{campaign&&<article><div className="campaign-head"><div><p className="eyebrow">{campaign.symbol} · {campaign.statusLabel}</p><h2>{campaign.name}</h2></div><button className="quiet mono" title={campaign.address} onClick={()=>navigator.clipboard.writeText(campaign.address).then(()=>setNotice('Campaign address copied.'))}>{short(campaign.address)}</button></div>
 <section className="panel funding"><div className="funding-top"><div><p className="label">Contributed</p><strong>{money(campaign.total)} <small>SOL</small></strong></div><div><p className="label">Launch target</p><strong>{money(campaign.target)} <small>SOL</small></strong></div></div><div className="progress" role="progressbar" aria-label="Funding toward target" aria-valuemin="0" aria-valuemax="100" aria-valuenow={Math.min(100,campaign.progress)}><span style={{width:Math.min(100,campaign.progress)+'%'}}/></div><p className="small">{campaign.progress>100?'Oversubscribed: if the launch executes, only the target is spent and excess SOL is returned proportionally.':'Anyone can contribute until the window closes. Allocation depends on the final total; fractional base units are rounded down.'}</p><div className="dates"><span>Funding closes <strong>{date(campaign.closeTime)}</strong></span><span>Settlement expires <strong>{date(campaign.expiry)}</strong></span></div></section>
 <div className="detail-grid"><section className="panel"><h3>Your commitment</h3><dl><div><dt>Contributed</dt><dd>{money(position?.contribution)} SOL</dd></div><div><dt>{campaign.status==='settled'?'Token entitlement':'Allocation estimate'}</dt><dd>{campaign.status==='settled'?money(position?.tokens,campaign.decimals)+' '+campaign.symbol:'Finalized at settlement'}</dd></div><div><dt>Excess refundable</dt><dd>{campaign.status==='settled'?money(position?.excess)+' SOL':'Calculated at close'}</dd></div></dl><p className="small">{position?.claimed?'Your entitlement has been claimed.':position?.refunded?'Your contribution has been refunded.':(position?'Claims and refunds are checked by the program.':'No outstanding contribution receipt for this wallet.')}</p>
 {campaign.canContribute&&<form onSubmit={e=>{e.preventDefault();prepare('contribute');}}><label>Contribution · SOL<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" autoComplete="off" required pattern="[0-9]+(\.[0-9]{1,9})?"/></label><button className="primary" disabled={!!busy}>Review contribution</button></form>}
 <div className="actions">{campaign.canWithdraw&&BigInt(position?.contribution||0)>0n&&<button onClick={()=>prepare('withdraw')} disabled={!!busy}>Withdraw contribution</button>}{campaign.canSettle&&<button className="primary" onClick={()=>prepare('settle')} disabled={!!busy}>Execute the launch</button>}{campaign.canRefund&&BigInt(position?.contribution||0)>0n&&!position?.refunded&&<button className="primary" onClick={()=>prepare('refund')} disabled={!!busy}>Recover contribution</button>}{campaign.status==='settled'&&BigInt(position?.contribution||0)>0n&&!position?.claimed&&<button className="primary" onClick={()=>prepare('claim')} disabled={!!busy}>Claim tokens & excess SOL</button>}</div>
 </section><section className="panel"><h3>What you are agreeing to</h3><ul className="terms"><li><span>Trading fee</span><strong>1%</strong></li><li><span>Migrated liquidity</span><strong>100% permanently locked</strong></li><li><span>Token supply</span><strong>{money(campaign.supply,campaign.decimals)} · fixed</strong></li><li><span>Setup costs</span><strong>Paid by organizer</strong></li><li><span>Allocation</span><strong>Proportional to contributions</strong></li></ul><details className="small"><summary>Verify the published terms</summary><dl><div><dt>Launch beneficiary</dt><dd className="mono break">{campaign.beneficiary}</dd></div><div><dt>Minimum tokens bought</dt><dd>{money(campaign.minTokens,campaign.decimals)} {campaign.symbol}</dd></div><div><dt>Migration threshold</dt><dd>{money(campaign.migrationThreshold)} SOL</dd></div><div><dt>Configuration</dt><dd className="mono break">{campaign.config}</dd></div><div><dt>Configuration hash</dt><dd className="mono break">{campaign.configHash}</dd></div></dl><p>{campaign.configMatches?"Configuration matches its committed hash.":"Configuration mismatch — settlement should reject."}</p><button onClick={()=>{const blob=new Blob([JSON.stringify({network:state.network,programId:state.programId,wallet:address,campaign},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="launch-terms.json";a.click();URL.revokeObjectURL(url);}}>Save terms & recovery addresses</button></details><p className="small">After Meteora’s protocol share, the launch beneficiary receives {campaign.creatorTradingFeePercentage}% of the remaining DBC trading fees; the partner recipient receives the rest. A shared first purchase can have a lower average price than later public purchases. This does not certify the token’s value.</p><p className="small">After successful settlement, tokens carry market risk. Principal refunds apply only to a launch that did not execute.</p></section></div>
 {campaign.status==='settled'&&<section className="panel"><h3>Continue trading</h3><p>Your balance: <strong>{money(campaign.walletTokenBalance,campaign.decimals)} {campaign.symbol}</strong></p><p>Venue: <strong>{campaign.venue||'DBC bonding curve'}</strong>. Quotes preserve an explicit minimum received.</p><form onSubmit={e=>{e.preventDefault();prepare('trade',{direction:tradeDirection});}} className="trade"><label>Direction<select aria-label="Direction" value={tradeDirection} onChange={e=>setTradeDirection(e.target.value)}><option value="buy">Buy token with SOL</option><option value="sell">Sell token for SOL</option></select></label><label>Amount · {tradeDirection==='buy'?'SOL':campaign.symbol}<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" autoComplete="off" required/></label><button disabled={!!busy}>Review trade</button></form>{campaign.canMigrate&&<button onClick={()=>prepare('migrate')} disabled={!!busy}>Complete DAMM v2 migration</button>}</section>}
 {LOCAL&&<details className="lab"><summary>Local rehearsal controls</summary><p>Move the synthetic clock to test deadlines. These controls do not exist on public networks.</p><div className="actions"><button disabled={!!busy} onClick={()=>perform('Advancing local clock',()=>api('advance',{campaign:selected,to:'close'}))}>Advance to funding close</button><button disabled={!!busy} onClick={()=>perform('Advancing local clock',()=>api('advance',{campaign:selected,to:'expiry'}))}>Advance to settlement expiry</button></div></details>}
 </article>}</div>}
 {preview&&<section ref={previewRef} tabIndex={-1} className="panel preview" role="region" aria-label="Transaction review"><p className="eyebrow">Review before signing</p><h2>{preview.title||preview.action}</h2><p>{preview.summary}</p>{preview.quoteDetails&&<p><strong>{preview.quoteDetails.minimumReceived?"Minimum received: "+money(preview.quoteDetails.minimumReceived,preview.quoteDetails.decimals)+" "+preview.quoteDetails.symbol:"Minimum first-purchase output: "+money(preview.quoteDetails.minimumTokens,preview.quoteDetails.decimals)+" tokens"}</strong></p>}<dl><div><dt>Network</dt><dd>{networkName}</dd></div><div><dt>Signer</dt><dd className="mono">{short(address)}</dd></div><div><dt>Network fee estimate</dt><dd>{money(preview.fee||5000)} test SOL</dd></div></dl><p className="small">{preview.note||'Only the displayed local test wallet signs. No real funds are used.'}</p><div className="actions"><button className="primary" disabled={!!busy} onClick={confirm}>{busy||(LOCAL?'Sign & submit local transaction':'Sign with wallet & submit')}</button><button disabled={!!busy} onClick={()=>setPreview(null)}>Cancel</button></div></section>}
 {receipt&&<details className="receipt"><summary>{receipt.status==='unknown'?'Transaction — confirmation unknown':receipt.status==='failed'?'Failed transaction':receipt.status==='rejected'?'Rejected before sending':'Confirmed transaction'} · {short(receipt.signature)}</summary><p className="mono break">{receipt.signature}</p><p>{receipt.compute?.toLocaleString()} compute units · {receipt.bytes} bytes · {networkName}{receipt.simulated?" · compute and logs from simulation":""}</p>{!LOCAL&&state?.network!=="validator"&&<a href={"https://explorer.solana.com/tx/"+receipt.signature+"?cluster=devnet"} target="_blank" rel="noreferrer">Check on Solana Explorer ↗</a>}<pre>{receipt.logs?.join('\n')}</pre></details>}
 <footer><span>Built around Meteora DBC → DAMM v2</span><span>Experimental implementation · not audited · no external usage claimed</span></footer></main></>;
}
const appRoot=import.meta.hot?(import.meta.hot.data.root??=createRoot(document.getElementById('root'))):createRoot(document.getElementById('root'));
appRoot.render(<App/>);
