from pathlib import Path
import html,json
r=Path(__file__).resolve().parents[1]
entry=(r/'submission/entry.md').read_text();script=(r/'submission/demo-script.md').read_text()
esc=html.escape
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Launch Commitments — submission package</title><style>body{font:16px/1.65 system-ui;background:#f5f6ee;color:#20251e;margin:0}main{max-width:980px;margin:auto;padding:40px 24px}h1{font-size:42px;letter-spacing:-.04em;line-height:1.1}h2{margin-top:36px}a{color:#315a24}nav{display:flex;gap:22px;flex-wrap:wrap}.note{padding:20px;background:#e5edda;border-left:4px solid #77935e}textarea{box-sizing:border-box;width:100%;min-height:550px;padding:22px;font:15px/1.65 system-ui;border:1px solid #cad0c1;border-radius:8px;background:white;color:#20251e}button{background:#315a24;color:white;border:0;padding:10px 18px;border-radius:6px;font:inherit;margin-bottom:12px;cursor:pointer}li{margin:8px 0}.small{font-size:13px;color:#566050}details{margin:24px 0}summary{cursor:pointer;font-weight:650}</style><main><p class="small">METEORA DBC BOUNTY · PREPARED 6 OCTOBER 2026</p><h1>Launch Commitments</h1><p>Agree on a Meteora launch. Execute it together—or recover your contribution.</p><nav><a href="../">Public evidence</a><a href="../app/">Interactive devnet app</a><a href="https://github.com/mahfuz67/launch-commitments">Source</a></nav><p class="note">Prepared for review, not submitted. Devnet tests are developer-operated. No mainnet traction, independent audit or new asset class is claimed.</p><h2>Project description and links</h2><button onclick="copyText('entry',this)">Copy entry</button><textarea id="entry" aria-label="Submission entry">'''+esc(entry)+'''</textarea><h2>Short demonstration script</h2><button onclick="copyText('script',this)">Copy script</button><textarea id="script" aria-label="Demo script">'''+esc(script)+'''</textarea><h2>Before sending</h2><ul><li>Confirm the hosted app and transaction links load.</li><li>Complete and record the real Phantom signing test; do not count the simulated provider test as equivalent.</li><li>Sign in to Superteam and verify the actual form fields, eligibility declarations and closing time.</li><li>Review the final public links and attach the demonstration.</li><li>Keep developer test activity separate from users or organic volume.</li></ul><details><summary>Evidence boundaries</summary><p>The October 5 manifest records launch and refunds. The October 6 migration manifest extends the same campaign through DBC graduation and a DAMM v2 sale. The program remains upgradeable. Customer demand is unvalidated. Public code and a working demo do not guarantee prize placement.</p></details><p class="small">The sponsor’s own listing controls requirements. No generic judging weights or implied mainnet requirement have been substituted.</p></main><script>async function copyText(id,b){try{await navigator.clipboard.writeText(document.getElementById(id).value);b.textContent='Copied'}catch{b.textContent='Select text and copy manually'}}</script></html>'''
(r/'submission/index.html').write_text(page)
(r/'docs/submission').mkdir(exist_ok=True)
(r/'docs/submission/index.html').write_text(page)
print('Submission artifact generated.')
